name: CreazyLib
version: '2.0-SNAPSHOT'
main: pl.creazy.creazylib.CreazyLib
api-version: '1.21'
authors: [Dawid Ratajczak]
website: creazy.pl
commands:
  item:
    description: get items
  economy:
    description: manage economy
  head:
    description: give heads
  setworld:
    description: set world
