name: CreazyLib
version: '1.0-SNAPSHOT'
main: pl.creazy.creazylib.CreazyLib
api-version: '1.21'
authors: [Dawid Ratajczak]
website: creazy.pl
commands:
  item:
    description: get items
  economy:
    description: manage economy
  test:
    description: test command
